# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
executorType: machine

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Run Exporters
          command: |
            docker pull geokodikas/ci-export-manager:master
            docker run  --memory=4000000000 -v $PWD/output:/opt/geokodikas/tmp -v /var/run/docker.sock:/var/run/docker.sock -i --net=host geokodikas/ci-export-manager:master < exports.yaml
            mkdir -p artifacts
            cp output/full_import* artifacts/

      - store_artifacts:
          path: ~/repo/artifacts

